// ... previous code ...

try {
  // Code inside the try block
} catch (e) {
  // Added empty catch block to handle potential errors
}

// ... rest of the code ...